-- AlterTable
ALTER TABLE "User" ADD COLUMN "tgFunnelAnchorAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "tgFunnel5mSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "tgFunnel10mIdleSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "tgFunnel40mSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "tgFunnel6hSent" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "OpsSetting" ADD COLUMN "tgFunnelNoteRuFileId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OpsSetting" ADD COLUMN "tgFunnelNoteEnFileId" TEXT NOT NULL DEFAULT '';
ALTER TABLE "OpsSetting" ADD COLUMN "tgFunnelNoteCapture" TEXT NOT NULL DEFAULT '';
