-- AlterTable
ALTER TABLE "User" ADD COLUMN "tgRulesShownAt" DATETIME;
ALTER TABLE "User" ADD COLUMN "tgRulesNudge10mSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "tgRulesNudge3hSent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "tgRulesNudge24hSent" BOOLEAN NOT NULL DEFAULT false;
