-- AlterTable
ALTER TABLE "User" ADD COLUMN "tgFunnelV2Preview" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "tgFunnelV2PreviewBalance" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "tgFunnelV2BlurTrialsUsed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN "tgFunnelV2RulesOk" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "OpsSetting" ADD COLUMN "tgFunnelV2Live" BOOLEAN NOT NULL DEFAULT false;
